/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = 'dzwgebfpnfqwlnpmuros';
export const publicAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6d2dlYmZwbmZxd2xucG11cm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1OTk4NjQsImV4cCI6MjA3ODE3NTg2NH0.IGuF7x5OTsIoaOT-JWHPkELsQCpwqtdAhx2dLyToB6w';
