export const templateData = [
    {
        id: 1,
        name: "Classic Vertical (Green)",
        headerBg: "bg-green-600",
        orientation: "Vertical",
        tags: ["Traditional", "Green"],
        features: ["School Logo", "Student Photo", "QR Code", "Blood Group", "Address", "Emergency Contact"],
    },
    {
        id: 2,
        name: "Classic Vertical (Blue)",
        headerBg: "bg-blue-600",
        orientation: "Vertical",
        tags: ["Traditional", "Blue"],
        features: ["Student Photo", "QR Code", "Address", "Emergency Contact"],
    },
    {
        id: 3,
        name: "Classic Vertical (Red)",
        headerBg: "bg-red-600",
        orientation: "Vertical",
        tags: ["Traditional", "Red"],
        features: ["Logo", "Blood Group", "QR Code", "Emergency Contact"],
    },
    {
        id: 4,
        name: "Modern Horizontal (Yellow)",
        headerBg: "bg-yellow-600",
        orientation: "Horizontal",
        tags: ["Modern", "Yellow"],
        features: ["Student Photo", "Blood Group", "Address"],
    },
    {
        id: 5,
        name: "Modern Horizontal (Purple)",
        headerBg: "bg-purple-600",
        orientation: "Horizontal",
        tags: ["Modern", "Purple"],
        features: ["QR Code", "Student Photo", "Address"],
    },
    {
        id: 6,
        name: "Modern Horizontal (Indigo)",
        headerBg: "bg-indigo-600",
        orientation: "Horizontal",
        tags: ["Modern", "Indigo"],
        features: ["Logo", "QR Code", "Emergency Contact"],
    },
    {
        id: 7,
        name: "Executive Vertical (Grey)",
        headerBg: "bg-gray-800",
        orientation: "Vertical",
        tags: ["Formal", "Black"],
        features: ["Photo", "Minimal Info", "Signature"],
    },
    {
        id: 8,
        name: "Minimal Vertical (Orange)",
        headerBg: "bg-orange-600",
        orientation: "Vertical",
        tags: ["Simple", "Bright"],
        features: ["Photo", "QR Code"],
    },
    {
        id: 9,
        name: "Teal Vertical (Modern)",
        headerBg: "bg-teal-600",
        orientation: "Vertical",
        tags: ["Sleek", "Teal"],
        features: ["Blood Group", "Address", "Photo"],
    },
    {
        id: 10,
        name: "Compact Horizontal (Red)",
        headerBg: "bg-red-700",
        orientation: "Horizontal",
        tags: ["Bold", "Compact"],
        features: ["Photo", "Signature", "Address"],
    },
    {
        id: 11,
        name: "Clean Horizontal (Blue)",
        headerBg: "bg-blue-800",
        orientation: "Horizontal",
        tags: ["Clean", "Professional"],
        features: ["QR Code", "Emergency Contact"],
    },
    {
        id: 12,
        name: "Gradient Horizontal (Green)",
        headerBg: "bg-gradient-to-r from-green-500 to-lime-600",
        orientation: "Horizontal",
        tags: ["Vibrant", "Modern"],
        features: ["Logo", "Photo", "QR Code"],
    },
    // New CSS-Based Templates
    {
        id: 13,
        name: "Wave Design (Blue)",
        orientation: "Vertical",
        tags: ["Artistic", "Blue"],
        features: ["Photo", "Wave Header", "Details"],
        cssLayout: "custom-1"
    },
    {
        id: 14,
        name: "Geometric (Orange)",
        orientation: "Vertical",
        tags: ["Modern", "Orange"],
        features: ["Photo", "Geometric", "Details"],
        cssLayout: "custom-2"
    },
    {
        id: 15,
        name: "Traditional Red (Custom)",
        orientation: "Vertical",
        tags: ["Traditional", "Red", "Custom"],
        features: ["Photo", "Details", "Signature"],
        cssLayout: "custom-3"
    }
];
