-- Add test school admin user
-- Email: school@test.com
-- Password: school123

INSERT INTO schools (
    school_name,
    school_code,
    email,
    phone,
    address,
    password,
    section,
    custom_id,
    created_at,
    updated_at
)
VALUES (
    'Test School',
    'TEST001',
    'school@test.com',
    '1234567890',
    '123 Test Street, Test City',
    '$2b$10$rOzJqKqKqKqKqKqKqKqKqOqKqKqKqKqKqKqKqKqKqKqKqKqKqKqKqK', -- Placeholder - will be replaced
    'Primary',
    'ash-sch-001',
    NOW(),
    NOW()
)
ON CONFLICT (email) DO NOTHING;

-- Note: The password hash above is a placeholder
-- The actual hash will be generated by the Node.js script

