import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../../ui/card';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '../../ui/dialog';
import { GreenSwitch } from '../../ui/GreenSwitch';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../ui/select';
import {
  Copy,
  Link as LinkIcon,
  Plus,
  ExternalLink,
  CheckCircle,
  Loader2,
  Share2,
} from 'lucide-react';
import axiosInstance from '@/api/axiosInstance';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';

interface FormLink {
  id: number;
  token: string;
  class_name: string;
  division: string;
  full_url: string;
  created_at: string;
  expires_at: string;
  is_active: boolean;
}

interface Division {
  class_name: string;
  division_name: string;
}

export function FormLinkManager() {
  const { t } = useTranslation();
  const [formLinks, setFormLinks] = useState<FormLink[]>([]);
  const [divisions, setDivisions] = useState<Division[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  useEffect(() => {
    fetchFormLinks();
  }, []);

  const fetchFormLinks = async () => {
    setIsLoading(true);
    try {
      const response = await axiosInstance.get('/api/form-links/my-links');
      if (response.data.success) {
        setFormLinks(response.data.data.links || []);
        setDivisions(response.data.data.divisions || []);
      }
    } catch (error) {
      console.error('Error fetching form links:', error);
      toast.error(t('studentForms.links.fetchError'));
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopyLink = (url: string, token: string) => {
    navigator.clipboard.writeText(url);
    setCopiedToken(token);
    toast.success(t('studentForms.links.copiedSuccess'));
    setTimeout(() => setCopiedToken(null), 2000);
  };

  const handleWhatsAppShare = (url: string) => {
    const message = t('studentForms.links.whatsappMessage', { url });
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  const handleToggleActive = (linkId: number, newActiveState: boolean) => {
    setFormLinks((currentLinks) =>
      currentLinks.map((link) =>
        link.id === linkId ? { ...link, is_active: newActiveState } : link
      )
    );
    // Future API call can be added here
  };

  // Create a map of existing links by class-division
  const linkMap = new Map(formLinks.map((link) => [`${link.class_name}-${link.division}`, link]));

  // Merge divisions with their links
  const divisionsWithLinks = divisions.map((div) => {
    const key = `${div.class_name}-${div.division_name}`;
    return {
      class_name: div.class_name,
      division_name: div.division_name,
      link: linkMap.get(key) || null,
    };
  });

  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-8">
          <div className="text-center text-gray-500">
            <Loader2 className="w-8 h-8 animate-spin mx-auto mb-2" />
            <p>{t('studentForms.links.loadingLinks')}</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <Card className="border rounded-lg bg-gray-100">
        <CardHeader>
          <CardTitle className="text-gray-900 text-xl">{t('studentForms.links.title')}</CardTitle>
          <p className="text-sm text-gray-600 mt-1">
            {t('studentForms.links.subtitle')}
          </p>
        </CardHeader>
        <CardContent className="px-12 bg-gray-100">
          {divisionsWithLinks.length === 0 ? (
            <div className="text-center py-8 bg-yellow-50 border border-yellow-200 rounded-lg">
              <LinkIcon className="w-12 h-12 mx-auto mb-3 text-yellow-400" />
              <p className="font-semibold text-gray-900">{t('studentForms.links.noClasses')}</p>
              <p className="text-sm mt-2 text-gray-700">
                {t('studentForms.links.contactAdmin')}
              </p>
              <p className="text-xs mt-2 text-gray-600">
                {t('studentForms.links.autoGenerated')}
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {divisionsWithLinks.map((item, index) => {
                const hasLink = item.link !== null;
                const linkToken = item.link?.token || '';
                const linkUrl = item.link?.full_url || '';

                return (
                  <div key={index} className="border rounded-lg p-4 mb-3 bg-white">
                    <div className="flex items-center justify-between mb-3">
                      <h3 className="text-gray-900 font-semibold">
                        {item.class_name} - {item.division_name}
                      </h3>
                      {hasLink && (
                        <div className="flex items-center space-x-2">
                          <GreenSwitch
                            id={`link-status-${item.link?.id}`}
                            checked={item.link?.is_active || false}
                            onCheckedChange={(newActiveState) => {
                              if (item.link) {
                                handleToggleActive(item.link.id, newActiveState);
                              }
                            }}
                            className="mr-2"
                          />
                          <label
                            htmlFor={`link-status-${item.link?.id}`}
                            className={`text-sm font-medium ${item.link?.is_active ? 'text-green-600' : 'text-gray-700'
                              }`}
                          >
                            {item.link?.is_active ? t('studentForms.links.active') : t('studentForms.links.inactive')}
                          </label>
                        </div>
                      )}
                    </div>
                    {hasLink ? (
                      <>
                        <div className="bg-gray-100 p-3 rounded border mb-3">
                          <p className="text-sm text-gray-900 break-all">{linkUrl}</p>
                        </div>
                        <div className="flex gap-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleCopyLink(linkUrl, linkToken)}
                            className="flex items-center gap-2"
                          >
                            {copiedToken === linkToken ? (
                              <>
                                <CheckCircle className="w-4 h-4 text-green-600" />
                                <span>{t('studentForms.links.copied')}</span>
                              </>
                            ) : (
                              <>
                                <Copy className="w-4 h-4" />
                                <span>{t('studentForms.links.copyLink')}</span>
                              </>
                            )}
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleWhatsAppShare(linkUrl)}
                            className="flex items-center gap-2 border-green-600 text-green-600 hover:bg-green-50"
                          >
                            <Share2 className="w-4 h-4" />
                            <span>{t('studentForms.links.share')}</span>
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => window.open(linkUrl, '_blank')}
                            className="flex items-center gap-2"
                          >
                            <ExternalLink className="w-4 h-4" />
                            <span>{t('studentForms.links.open')}</span>
                          </Button>
                        </div>
                      </>
                    ) : (
                      <p className="text-sm text-gray-600">
                        {t('studentForms.links.linkAutoGenerate')}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
